import { getSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import type { CompanyBundle, CompanyContent } from "@/types/company";
import type { Database } from "@/types/database";
const empty=():CompanyBundle=>({content:null,history:[],values:[],statistics:[],partners:[],legalEntities:[],certifications:[],organization:[]});
const client=()=>{if(!isSupabaseConfigured)throw new Error("Supabase is not configured for company content.");return getSupabaseClient();};
const mapContent=(r:Database["public"]["Tables"]["company_content"]["Row"]):CompanyContent=>({id:r.id,overview:r.overview,vision:r.vision,mission:r.mission,objectives:r.objectives,duties:r.duties,approach:r.approach,ownershipAccountability:r.ownership_accountability,headOffice:r.head_office,seoTitle:r.seo_title,seoDescription:r.seo_description,status:r.status,updatedAt:r.updated_at});
export async function getCompanyContent(){if(!isSupabaseConfigured)return null;try{const {data,error}=await getSupabaseClient().from("company_content").select("*").eq("content_key","primary").maybeSingle();if(error)throw error;return data?mapContent(data):null;}catch(e){console.warn("Unable to load company content",e);return null;}}
export async function getCompanyBundle():Promise<CompanyBundle>{if(!isSupabaseConfigured)return empty();try{const db=client();const [content,history,values,statistics,partners,legalEntities,certifications,organization]=await Promise.all([getCompanyContent(),db.from("company_history").select("*").order("sort_order"),db.from("company_values").select("*").order("sort_order"),db.from("company_statistics").select("*").order("sort_order"),db.from("company_partners").select("*").order("sort_order"),db.from("company_legal_entities").select("*").order("sort_order"),db.from("company_certifications").select("*").order("sort_order"),db.from("company_organization").select("*").order("sort_order")]);for(const x of [history,values,statistics,partners,legalEntities,certifications,organization])if(x.error)throw x.error;return {content,history:(history.data??[]).map(r=>({id:r.id,title:r.title,description:r.description,yearLabel:r.year_label,sortOrder:r.sort_order,status:r.status,active:r.status==="published"})),values:(values.data??[]).map(r=>({id:r.id,title:r.title,description:r.description,sortOrder:r.sort_order,active:r.active})),statistics:(statistics.data??[]).map(r=>({id:r.id,label:r.label,displayValue:r.display_value,description:r.description,sortOrder:r.sort_order,active:r.active})),partners:(partners.data??[]).map(r=>({id:r.id,title:r.name,description:r.description??"",sortOrder:r.sort_order,active:r.active,shortName:r.short_name,category:r.category,logoUrl:r.logo_url,website:r.website})),legalEntities:(legalEntities.data??[]).map(r=>({id:r.id,title:r.name,description:r.description??"",sortOrder:r.sort_order,active:r.active,imageUrl:r.image_url,documentType:r.document_type,reference:r.reference})),certifications:(certifications.data??[]).map(r=>({id:r.id,title:r.name,description:r.description??"",sortOrder:r.sort_order,active:r.active,imageUrl:r.image_url,certificationType:r.certification_type,issuingOrganization:r.issuing_organization,issueDate:r.issue_date})),organization:(organization.data??[]).map(r=>({id:r.id,title:r.position,description:r.biography??"",sortOrder:r.sort_order,active:r.active,name:r.name,position:r.position,department:r.department,parentPosition:r.parent_position,photoUrl:r.photo_url}))};}catch(e){console.warn("Unable to load company CMS",e);return empty();}}
export const getPartners=async()=> (await getCompanyBundle()).partners; export const getStatistics=async()=> (await getCompanyBundle()).statistics;
export async function updateCompanyContent(id:string,payload:Database["public"]["Tables"]["company_content"]["Update"]){const {error}=await client().from("company_content").update(payload).eq("id",id);if(error)throw error;}
type CompanyCollection="company_history"|"company_values"|"company_statistics"|"company_partners"|"company_legal_entities"|"company_certifications"|"company_organization";
export async function createCompanyItem(table:CompanyCollection,payload:Record<string,unknown>){const {error}=await client().from(table).insert(payload as never);if(error)throw error;}
export async function deleteCompanyItem(table:CompanyCollection,id:string){const {error}=await client().from(table).delete().eq("id",id);if(error)throw error;}
