import { Link, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { ArrowRight } from "lucide-react";
import Seo from "@/components/Seo";
import Breadcrumbs from "@/components/Breadcrumbs";
import AnimatedSection from "@/components/AnimatedSection";
import { getLocalizedServiceBySlug, getServicesBySlugs, serviceContent } from "@/data/services";
import { formatBirr } from "@/lib/formatBirr";
import { getProjects } from "@/services/projectService";
import type { Project } from "@/types/project";
import { absoluteUrl, companyData, SITE_URL } from "@/config/site";
import { useI18n } from "@/i18n";

const ServiceDetail = () => {
  const { slug = "" } = useParams(); const { locale, path } = useI18n(); const am = locale === "am";
  const service = getLocalizedServiceBySlug(slug, locale); const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); void getProjects(undefined, locale).then((result) => active && setProjects(result)).catch(() => active && setProjects([])).finally(() => active && setLoading(false)); return () => { active = false; }; }, [locale]);
  const copy = am ? { home: "መነሻ", services: "አገልግሎቶች", construction: "የግንባታ አገልግሎቶች", capabilities: "አቅሞች", evidence: "ማስረጃ", related: "ተዛማጅ ፕሮጀክቶች", allProjects: "ሁሉንም የግንባታ ፕሮጀክቶች ይመልከቱ", other: "ሌሎች አገልግሎቶች", cta: "ስለ ፕሮጀክትዎ ከእኛ ጋር ይወያዩ", ctaText: "ሂቢር ኮንስትራክሽን ኮርፖሬሽን ከፌዴራል፣ ከክልልና ከከተማ ደንበኞች ጋር ይሠራል።", contact: "HIBIRን ያግኙ", missingTitle: "አገልግሎቱ አልተገኘም", missingText: "ይህ አገልግሎት በአማርኛ እንዲታተም የጸደቀ ይዘት የለውም።", back: "ወደ አገልግሎቶች ተመለስ", loading: "አገልግሎቱን በመጫን ላይ…" } : { home: "Home", services: "Services", construction: "Construction services", capabilities: "Capabilities", evidence: "Evidence", related: "Related projects", allProjects: "View all construction projects", other: "Other Services", cta: "Discuss your project", ctaText: "Hibir Construction Corporation works with federal, regional and city clients from its head office in Bahir Dar, Amhara Regional State.", contact: "Contact Hibir", missingTitle: "Service not found", missingText: "This service may have moved or is not publicly available.", back: "Back to Services", loading: "Loading service…" };
  const pagePath = path(`/services/${slug}`);
  if (!service) return <main className="min-h-screen grid place-items-center px-6 text-center"><Seo title={`${copy.missingTitle} | Hibir Construction Corporation`} description={copy.missingText} path={pagePath} noindex /><div><h1 className="font-display font-bold text-3xl text-foreground mb-4">{copy.missingTitle}</h1><p className="mb-8 text-muted-foreground">{copy.missingText}</p><Link to={path("/services")} className="btn-accent text-sm">{copy.back}</Link></div></main>;
  const content = serviceContent(service, locale); const relatedProjects = projects.filter((p) => (service.projectCategories as string[]).includes(p.category)).slice(0, 4); const relatedServices = getServicesBySlugs([...service.relatedServices]).filter((s) => locale === "en" || Boolean(s.amharic)).map((s) => serviceContent(s, locale));
  const crumbs = [{ name: copy.home, path: path("/") }, { name: copy.services, path: path("/services") }, { name: content.name, path: pagePath }];
  return <main><Seo title={content.seoTitle} description={content.seoDescription} path={pagePath} image={content.heroImage} breadcrumbs={crumbs} jsonLd={{ "@context": "https://schema.org", "@type": "Service", name: content.name, serviceType: content.name, description: content.description, url: absoluteUrl(pagePath), inLanguage: locale === "am" ? "am" : "en", areaServed: companyData.areasServed.map((a) => ({ "@type": "Place", name: a })), provider: { "@id": `${SITE_URL}/#organization` } }} />
    <section className="relative pt-32 pb-14 px-4 md:px-8 overflow-hidden"><div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-background to-transparent" aria-hidden /><div className="container-custom relative max-w-4xl"><Breadcrumbs crumbs={crumbs} className="mb-8" /><span className="label-eyebrow">{copy.construction}</span><h1 className="font-display font-bold text-3xl md:text-5xl leading-tight tracking-tight text-foreground mt-4">{content.h1}</h1><p className="mt-6 text-lg text-muted-foreground font-body leading-relaxed">{content.description}</p></div></section>
    <div className="px-4 md:px-8"><figure className="container-custom max-w-5xl"><img src={content.heroImage} alt={content.heroImageAlt} loading="lazy" className="w-full aspect-[16/9] object-cover rounded-3xl border border-border" /></figure></div>
    <section className="section-padding"><div className="container-custom max-w-4xl space-y-12">{content.sections.map((s) => <AnimatedSection key={s.heading}><h2 className="font-display font-bold text-2xl text-foreground mb-3">{s.heading}</h2><p className="text-muted-foreground font-body leading-relaxed">{s.body}</p></AnimatedSection>)}<AnimatedSection><h2 className="font-display font-bold text-2xl text-foreground mb-4">{copy.capabilities}</h2><ul className="grid sm:grid-cols-2 gap-3">{content.capabilities.map((c) => <li key={c} className="rounded-xl border border-border px-4 py-3 text-sm font-body text-muted-foreground">{c}</li>)}</ul></AnimatedSection></div></section>
    {loading ? <div className="sr-only" role="status">{copy.loading}</div> : relatedProjects.length > 0 && <section className="section-padding border-t border-border"><div className="container-custom"><span className="label-eyebrow">{copy.evidence}</span><h2 className="section-title mt-3 mb-10">{copy.related}</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{relatedProjects.map((p) => <Link key={p.id} to={path(`/projects/${p.slug}`)} className="group rounded-2xl border border-border overflow-hidden hover:border-accent/50 transition-colors"><img src={p.featuredImage.url} alt={locale === "am" ? (p.titleAm ?? "") : p.featuredImage.alt} loading="lazy" className="w-full aspect-[4/3] object-cover group-hover:scale-105 transition-transform duration-700" /><div className="p-4"><h3 className="font-display font-semibold text-sm text-foreground leading-snug">{locale === "am" ? p.titleAm : p.title}</h3><p className="mt-2 text-xs font-body text-muted-foreground">{p.location} · {formatBirr(p.contractValue)} · {p.status}</p></div></Link>)}</div><Link to={path("/projects")} className="inline-flex items-center gap-2 mt-8 text-sm font-body font-semibold text-accent">{copy.allProjects}<ArrowRight size={16} /></Link></div></section>}
    <section className="section-padding border-t border-border"><div className="container-custom max-w-4xl"><h2 className="section-title mb-8">{copy.other}</h2><div className="flex flex-wrap gap-3">{relatedServices.map((s) => <Link key={s.id} to={path(s.canonicalUrl)} className="rounded-full border border-border px-5 py-2 text-sm font-body text-muted-foreground hover:text-accent hover:border-accent/50 transition-colors">{s.name}</Link>)}</div><div className="mt-12 rounded-3xl border border-border p-8 md:p-10"><h2 className="font-display font-bold text-2xl text-foreground">{copy.cta}</h2><p className="text-muted-foreground font-body mt-3 max-w-2xl">{copy.ctaText}</p><Link to={path("/contact")} className="btn-accent text-sm inline-flex items-center gap-2 mt-6">{copy.contact}<ArrowRight size={16} /></Link></div></div></section>
  </main>;
}; export default ServiceDetail;
