import { ArrowLeft, Save, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { createNews, getAdminNewsById, publishNews, updateNews } from "@/services/newsService";
import { NEWS_CATEGORIES, type CreateNewsInput, type NewsBlock, type NewsStatus } from "@/types/news";

const empty = (): CreateNewsInput => ({ title: "", slug: "", excerpt: "", content: [], category: "Company News", coverImage: "", featured: false, status: "draft", seoTitle: "", seoDescription: "" });
const blocksText = (blocks: NewsBlock[]) => JSON.stringify(blocks, null, 2);

export default function AdminNewsEditor() {
  const { id } = useParams(); const navigate = useNavigate();
  const [input, setInput] = useState<CreateNewsInput>(empty); const [content, setContent] = useState("[]");
  const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!id) return; void (async () => { try { const article = await getAdminNewsById(id); if (!article) { setError("This news article could not be found."); return; } setInput({ title: article.title, slug: article.slug, excerpt: article.excerpt, content: article.content, category: article.category, coverImage: article.featuredImage.url, featured: article.featured, status: article.status, publishedAt: article.publishedAt, seoTitle: article.seoTitle ?? "", seoDescription: article.seoDescription ?? "" }); setContent(blocksText(article.content)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load the news article."); } finally { setLoading(false); } })(); }, [id]);
  const set = <K extends keyof CreateNewsInput>(key: K, value: CreateNewsInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const save = async (publish = false) => { let parsed: NewsBlock[]; try { parsed = JSON.parse(content) as NewsBlock[]; if (!Array.isArray(parsed)) throw new Error(); } catch { setError("Content must be a JSON array of article blocks."); return; } setSaving(true); setError(""); try { const payload = { ...input, content: parsed, status: publish ? "published" as NewsStatus : input.status }; const article = id ? await updateNews(id, payload) : await createNews(payload); if (publish && id) await publishNews(article.id); toast.success(publish ? "News article published." : "News article saved."); navigate(`/admin/news/${article.id}/edit`, { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save the news article."); } finally { setSaving(false); } };
  if (loading) return <div className="surface-card p-10 text-center text-muted-foreground">Loading news article…</div>;
  return <div className="mx-auto max-w-4xl space-y-6"><div><Button asChild variant="ghost" className="-ml-3 gap-2"><Link to="/admin/news"><ArrowLeft size={17} />Back to News</Link></Button><p className="mt-4 label-eyebrow">Newsroom</p><h1 className="mt-2 font-display text-3xl font-semibold">{id ? "Edit News" : "Create News"}</h1></div>{error && <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="surface-card space-y-6 p-5 md:p-7"><div className="grid gap-5 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><Label htmlFor="title">Title</Label><Input id="title" value={input.title} onChange={(event) => set("title", event.target.value)} /></div><div className="space-y-2"><Label htmlFor="slug">Slug</Label><Input id="slug" value={input.slug} onChange={(event) => set("slug", event.target.value)} /></div><div className="space-y-2"><Label>Category</Label><Select value={input.category} onValueChange={(value) => set("category", value as CreateNewsInput["category"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{NEWS_CATEGORIES.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 md:col-span-2"><Label htmlFor="excerpt">Excerpt</Label><Textarea id="excerpt" value={input.excerpt} onChange={(event) => set("excerpt", event.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label htmlFor="cover">Cover image URL</Label><Input id="cover" type="url" value={input.coverImage} onChange={(event) => set("coverImage", event.target.value)} placeholder="https://…" /></div><div className="space-y-2 md:col-span-2"><Label htmlFor="content">Content blocks (JSON)</Label><Textarea id="content" className="min-h-52 font-mono text-xs" value={content} onChange={(event) => setContent(event.target.value)} /><p className="text-xs text-muted-foreground">Use the existing safe block format, for example [{'{'}"type":"paragraph","text":"…"{'}'}].</p></div><div className="space-y-2"><Label htmlFor="seoTitle">SEO title</Label><Input id="seoTitle" value={input.seoTitle} onChange={(event) => set("seoTitle", event.target.value)} /></div><div className="space-y-2"><Label htmlFor="seoDescription">SEO description</Label><Input id="seoDescription" value={input.seoDescription} onChange={(event) => set("seoDescription", event.target.value)} /></div></div><div className="flex flex-col gap-3 border-t pt-5 sm:flex-row sm:justify-end"><Button variant="outline" disabled={saving} onClick={() => void save(false)} className="gap-2"><Save size={16} />{saving ? "Saving…" : "Save"}</Button><Button disabled={saving} onClick={() => void save(true)} className="gap-2"><Send size={16} />Publish</Button></div></div></div>;
}
