import { Clipboard, ImagePlus, Loader2 } from "lucide-react";
import { useEffect, useState, type ChangeEvent } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { validateImageFile } from "@/lib/newsEditor";
import { getNewsMedia, uploadNewsImage, type MediaAsset } from "@/services/newsService";

/** Focused, non-destructive library for the public news-media bucket. */
export default function AdminMedia() {
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [selected, setSelected] = useState<MediaAsset | null>(null);
  const load = async () => { setLoading(true); try { setAssets(await getNewsMedia()); } catch { toast.error("Unable to load the media library."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const issue = validateImageFile(file); if (issue) return toast.error(issue); setUploading(true); try { await uploadNewsImage("library", file); toast.success("Image uploaded to the library."); await load(); } catch { toast.error("Image upload failed. Please try again."); } finally { setUploading(false); } };
  const copy = async (url: string) => { try { await navigator.clipboard.writeText(url); toast.success("Image URL copied."); } catch { toast.error("Could not copy the image URL."); } };
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="label-eyebrow">Newsroom</p><h1 className="mt-2 font-display text-3xl font-semibold">Media library</h1><p className="mt-2 text-sm text-muted-foreground">Reusable news images. Images are never deleted here because they may be used by an article.</p></div><label className="inline-flex cursor-pointer"><Button asChild disabled={uploading}><span className="gap-2"><ImagePlus size={16}/>{uploading ? "Uploading…" : "Upload image"}</span></Button><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div><p className="text-xs text-muted-foreground">JPEG, PNG, and WebP up to 8 MB. Select an existing image from the News Editor using its URL; permanent deletion is intentionally unavailable.</p>{loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-accent"/></div> : assets.length === 0 ? <div className="surface-card p-16 text-center"><p className="font-display text-lg font-semibold">No media uploaded yet</p><p className="mt-2 text-sm text-muted-foreground">Upload an image to make it available to the News CMS.</p></div> : <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{assets.map((asset) => <button type="button" key={asset.path} onClick={() => setSelected(asset)} className="overflow-hidden rounded-xl border bg-background text-left hover:border-accent"><img src={asset.url} alt="" className="aspect-square w-full object-cover" onError={(e) => { e.currentTarget.classList.add("hidden"); }}/><span className="block truncate p-3 text-xs font-medium">{asset.name}</span></button>)}</div>}<Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.name}</DialogTitle></DialogHeader>{selected && <div className="space-y-4"><img src={selected.url} alt={selected.name} className="max-h-[55vh] w-full rounded-lg object-contain"/><dl className="grid grid-cols-2 gap-2 text-sm"><dt className="text-muted-foreground">Uploaded</dt><dd>{selected.createdAt ? new Date(selected.createdAt).toLocaleDateString() : "Unavailable"}</dd><dt className="text-muted-foreground">Size</dt><dd>{selected.size ? `${Math.ceil(selected.size / 1024)} KB` : "Unavailable"}</dd></dl><Button type="button" variant="outline" className="gap-2" onClick={() => void copy(selected.url)}><Clipboard size={16}/>Copy image URL</Button></div>}</DialogContent></Dialog></div>;
}
