import { Activity, ArrowRight, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { formatAdminRole } from "@/lib/admin";
import { useAuth } from "@/contexts/AuthContext";

export default function AdminDashboard() {
  const { adminProfile, session } = useAuth();
  const name = adminProfile?.full_name || adminProfile?.email || "Administrator";
  return <div className="space-y-8"><div><p className="label-eyebrow">Dashboard</p><h1 className="mt-2 text-3xl font-semibold">Welcome, {name}</h1><p className="mt-2 text-muted-foreground">Your administrator workspace is ready.</p></div><div className="grid gap-5 md:grid-cols-2"><section className="surface-card p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-success" /><h2 className="font-display text-lg font-semibold">Administrator access</h2></div><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Role</dt><dd className="font-medium">{adminProfile && formatAdminRole(adminProfile.role)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Session</dt><dd className="font-medium text-success">Active</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Account</dt><dd className="max-w-[60%] truncate font-medium">{session?.user.email}</dd></div></dl></section><section className="surface-card p-6"><div className="flex items-center gap-3"><Activity className="text-accent" /><h2 className="font-display text-lg font-semibold">Content statistics</h2></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Content statistics will appear after CMS modules are enabled.</p></section></div><section className="surface-card p-6"><h2 className="font-display text-lg font-semibold">Quick actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Link to="/admin/news" className="flex items-center justify-between rounded-lg border border-border p-4 text-sm font-medium hover:bg-muted">Manage news <ArrowRight size={16} /></Link><Link to="/admin/projects" className="flex items-center justify-between rounded-lg border border-border p-4 text-sm font-medium hover:bg-muted">Manage projects <ArrowRight size={16} /></Link></div></section></div>;
}
